baseURL = 'https://ta180m.github.io/'
languageCode = 'en-us'
title = 'Some Random Website'
theme = 'gokarna'

[menu]
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    pre = '<span data-feather="aperture"></span>'
    weight = 1
  [[menu.main]]
    identifier = 'projects'
    name = 'Projects'
    url = '/projects/'
    pre = '<span data-feather="package"></span>'
    weight = 2
  [[menu.main]]
    identifier = 'posts'
    name = 'Posts'
    url = '/posts/'
    pre = '<span data-feather="book"></span>'
    weight = 3
  [[menu.main]]
    identifier = 'tags'
    name = 'Tags'
    url = '/tags/'
    pre = '<span data-feather="tag"></span>'
    weight = 4
  [[menu.main]]
    identifier = 'feed'
    name = 'Feed'
    url = '/index.xml'
    pre = '<span data-feather="rss"></span>'
    weight = 5
  [[menu.main]]
    identifier = 'github'
    name = 'GitHub'
    url = 'https://github.com/Ta180m/ta180m.github.io'
    pre = '<span data-feather="github"></span>'
    weight = 6

[params]
  avatarURL = '/dodecahedra/render-small.gif'
  avatarSize = 'size-xl'
  description = 'Hello! I’m Anthony Wang, a programming, math, and science enthusiast!'
  accentColor = '#00dd42'
  footer = 'Made with ❤️ by Ta180m - CC BY-SA 4.0'
  socialIcons = [
      {name = 'protonmail', url = '/about/contact'},
      {name = 'matrix', url = 'https://matrix.to/#/@ta180m:exozy.me'},
      {name = 'mastodon', url = 'https://social.exozy.me/@ta180m'},
      {name = 'peertube', url = 'https://tube.exozy.me/a/ta180m/video-channels'},
      {name = 'gitea', url = 'https://git.exozy.me/Ta180m/'},
      {name = 'github', url = 'https://github.com/Ta180m/'},
      {name = 'codeforces', url = 'https://codeforces.com/profile/Ta180m'},
      {name = 'archlinux', url = 'https://aur.archlinux.org/packages/?K=Ta180m&SeB=m'},
    ]
