baseURL = 'https://a.exozy.me'
languageCode = 'en-us'
title = 'Some Random Website'
theme = 'gokarna'

[menu]
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    pre = '<span data-feather="aperture"></span>'
    weight = 1
  [[menu.main]]
    identifier = 'projects'
    name = 'Projects'
    url = '/projects/'
    pre = '<span data-feather="package"></span>'
    weight = 2
  [[menu.main]]
    identifier = 'posts'
    name = 'Posts'
    url = '/posts/'
    pre = '<span data-feather="book"></span>'
    weight = 3
  [[menu.main]]
    identifier = 'tags'
    name = 'Tags'
    url = '/tags/'
    pre = '<span data-feather="tag"></span>'
    weight = 4
  [[menu.main]]
    identifier = 'feed'
    name = 'Feed'
    url = '/index.xml'
    pre = '<span data-feather="rss"></span>'
    weight = 5
  [[menu.main]]
    identifier = 'git'
    name = 'Git'
    url = 'https://git.exozy.me/a/website'
    pre = '<span data-feather="git-pull-request"></span>'
    weight = 6

[params]
  avatarURL = '/dodecahedra/logo.webp'
  avatarSize = 'size-xl'
  description = '(+ (This subdomain) (Ordinal n) (! off) (Element 39) (Wide area network) (Prefix for billion))'
  accentColor = '#00dd42'
  footer = '🎉 Made with Hugo and frustration! - CC BY-SA 4.0'
  togglePreviousAndNextButtons = 'true'
  socialIcons = [
      {name = 'email', url = '/about/email', rel = 'me'},
      {name = 'forgejo', url = 'https://git.exozy.me/a', rel = 'me'},
      {name = 'codeberg', url = 'https://codeberg.org/xy', rel = 'me'},
      {name = 'mastodon', url = 'https://social.exozy.me/@a', rel = 'me'},
      {name = 'peertube', url = 'https://tube.exozy.me/a/a/video-channels', rel = 'me'},
      {name = 'matrix', url = 'https://matrix.to/#/@a:exozy.me', rel = 'me'},
      {name = 'archlinux', url = 'https://aur.archlinux.org/packages/?K=dodecahedron&SeB=m', rel = 'me'},
      {name = 'codeforces', url = 'https://codeforces.com/profile/Ta180m', rel = 'me'},
      {name = 'liberapay', url = 'https://liberapay.com/xy/', rel = 'me'},
    ]
